service: azure-functions-app1234

provider:
  name: azure
  location: West US
  #armTemplate:
     #file: YourARMTemplate.json
     #parameters:
      #VariableNameToUserInArmTemplate: Value

plugins:
  - serverless-azure-functions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - package.json
    - .git/**

functions:
  httpjs: 
     handler: handler.hello
     events: 
       - http: true
         x-azure-settings:
           authLevel : anonymous
           
  queuejs: 
     handler: handler.helloQueue
     events: 
       - queue: SampleQueue
         x-azure-settings:
           name: queueItem
           connection : AzureWebJobsStorage
       - blob:
         x-azure-settings:
           name: blobOut
           direction: out
           connection : AzureWebJobsStorage
     
 