service: azure-functions-service 

provider:
  name: azure
  runtime: nodejs4.3
  subscriptionId: YourSubscriptionID
  resourceGroupName: YourResourceGroupName
  deploymentName: YourDeploymentName
  functionAppName: YourFunctionAppName
  gitUrl: GitUrlWithFunctionCode.Note URL needs to include git accesscode

plugins:
  - serverless-azure-functions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - package.json
    - .git/**

functions:
  httpcsharp:
    handler: http
    events:
      - http: true
 