service: azure-functions-service # NOTE: Don't put the word "google" in here

provider:
  name: azure
  runtime: nodejs4.3
  
plugins:
  - serverless-azure-functions

# needs more granular excluding in production as only the serverless provider npm
# package and it's dependencies should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - package.json
    - .git/**

functions:
  first:
    handler: http
    events:
      - http: true
  # NOTE: Please create the bucket first, then comment this out and deploy again
  #third:
  #  handler: bucket
  #  events:
  #    - bucket: my-serverless-test-bucket
