service: azure-functions-service 

provider:
  name: azure
  subscriptionId: YourAzureSubscriptionID
  servicePrincipalTenantId: servicePrincipalTenantId
  servicePrincipalClientId: servicePrincipalClientId
  servicePrincipalPassword: servicePrincipalPassword
  functionAppName: YourFunctionAppName
  location: West US
  gitUrl: GitUrlWithFunctionCode.Note URL needs to include git accesscode
plugins:
  - serverless-azure-functions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - package.json
    - .git/**

functions:
  httpcsharp:
    triggerType: httpTrigger
  queueTriggerCSharp:
    triggerType: queueTrigger
     
 