service: azure-functions-service 

provider:
  name: azure
  subscriptionId: azureSubId
  servicePrincipalTenantId: azureServicePrincipalTenantId
  servicePrincipalClientId: azureservicePrincipalClientId
  servicePrincipalPassword: azureServicePrincipalPassword
  location: West US
plugins:
  - serverless-azure-functions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - package.json
    - .git/**

functions:
  httpjs: 
     handler: templates/handler.hello
     events: 
       - http: true
       - authLevel: anonymous
  queuejs: 
     handler: templates/handler.helloQueue
     events: 
       - queue: js-queue-serverless
           
     
 