service: azure-functions-service 

provider:
  name: azure
  runtime: nodejs4.3
  
plugins:
  - serverless-azure-functions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - package.json
    - .git/**

functions:
  first:
    handler: http
    events:
      - http: true
 