service: gcf-service # NOTE: Don't put the word "google" in here

provider:
  name: google
  runtime: nodejs4.3
  project: my-project-1234
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package and it's dependencies should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - package.json
    - .git/**

functions:
  fist:
    handler: pubSub
    events:
      - pubSub: someTopicName
  second:
    handler: http
    events:
      - http: true
  # NOTE: Please create the bucket first, then comment this out and deploy again
  #third:
  #  handler: bucket
  #  events:
  #    - bucket: my-serverless-test-bucket
