service: azure-functions-app

provider:
  name: azure
  location: West US
  #armTemplate:
     #file: YourARMTemplate.json
     #parameters:
      #VariableNameToUserInArmTemplate: Value

plugins:
  - serverless-azure-functions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - package.json
    - .git/**

functions:
  httpjs: 
     handler: templates/handler.hello
     events: 
       - http: true
         x-azure-settings:
           authLevel : anonymous
           
  queuejs: 
     handler: templates/handler.helloQueue
     events: 
       - queue: YourQueueName
         x-azure-settings:
           connection : StorageAppSettingName
       - blob:
         x-azure-settings:
           name: bindingName
           direction: in
   
  httpwebhookjs: 
     handler: templates/handler.hello
     events: 
       - http: true
         x-azure-settings:
           webHookType : gitHub
  #eventHubjs: 
     #handler: templates/handler.hello
     #events: 
       #- eventHub:
       #  x-azure-settings:
       #   connection : AppSettingSetViaArmTemplate
     
 